/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/asistente': typeof AsistenteRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/perfil': typeof PerfilRoute
  '/tienda': typeof TiendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/asistente': typeof AsistenteRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/perfil': typeof PerfilRoute
  '/tienda': typeof TiendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/asistente': typeof AsistenteRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/perfil': typeof PerfilRoute
  '/tienda': typeof TiendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/asistente'
    | '/cursos'
    | '/dashboard'
    | '/perfil'
    | '/tienda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/asistente'
    | '/cursos'
    | '/dashboard'
    | '/perfil'
    | '/tienda'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/asistente'
    | '/cursos'
    | '/dashboard'
    | '/perfil'
    | '/tienda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AsistenteRoute: typeof AsistenteRoute
  CursosRoute: typeof CursosRoute
  DashboardRoute: typeof DashboardRoute
  PerfilRoute: typeof PerfilRoute
  TiendaRoute: typeof TiendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AsistenteRoute: AsistenteRoute,
  CursosRoute: CursosRoute,
  DashboardRoute: DashboardRoute,
  PerfilRoute: PerfilRoute,
  TiendaRoute: TiendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
