/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalaProRouteImport } from './routes/sala-pro'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ReembolsosRouteImport } from './routes/reembolsos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HerramientasRouteImport } from './routes/herramientas'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HerramientasIndexRouteImport } from './routes/herramientas.index'
import { Route as HerramientasPuntoEquilibrioRouteImport } from './routes/herramientas.punto-equilibrio'
import { Route as HerramientasMonitorCmvRouteImport } from './routes/herramientas.monitor-cmv'
import { Route as HerramientasFichasTecnicasRouteImport } from './routes/herramientas.fichas-tecnicas'
import { Route as HerramientasDreMensualRouteImport } from './routes/herramientas.dre-mensual'
import { Route as HerramientasDreRouteImport } from './routes/herramientas.dre'
import { Route as HerramientasControlCajaRouteImport } from './routes/herramientas.control-caja'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CursosIdRouteImport } from './routes/cursos_.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicProEmbedRouteImport } from './routes/api.public.pro-embed'
import { Route as ApiPublicNovedadesRouteImport } from './routes/api.public.novedades'
import { Route as ApiPublicMaterialDownloadRouteImport } from './routes/api.public.material-download'
import { Route as ApiPublicLessonEmbedRouteImport } from './routes/api.public.lesson-embed'
import { Route as ApiPublicBunnyThumbsRouteImport } from './routes/api.public.bunny-thumbs'
import { Route as ApiPublicBunnySyncRouteImport } from './routes/api.public.bunny-sync'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaProRoute = SalaProRouteImport.update({
  id: '/sala-pro',
  path: '/sala-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsosRoute = ReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasRoute = HerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasIndexRoute = HerramientasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HerramientasRoute,
} as any)
const HerramientasPuntoEquilibrioRoute =
  HerramientasPuntoEquilibrioRouteImport.update({
    id: '/punto-equilibrio',
    path: '/punto-equilibrio',
    getParentRoute: () => HerramientasRoute,
  } as any)
const HerramientasMonitorCmvRoute = HerramientasMonitorCmvRouteImport.update({
  id: '/monitor-cmv',
  path: '/monitor-cmv',
  getParentRoute: () => HerramientasRoute,
} as any)
const HerramientasFichasTecnicasRoute =
  HerramientasFichasTecnicasRouteImport.update({
    id: '/fichas-tecnicas',
    path: '/fichas-tecnicas',
    getParentRoute: () => HerramientasRoute,
  } as any)
const HerramientasDreMensualRoute = HerramientasDreMensualRouteImport.update({
  id: '/dre-mensual',
  path: '/dre-mensual',
  getParentRoute: () => HerramientasRoute,
} as any)
const HerramientasDreRoute = HerramientasDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => HerramientasRoute,
} as any)
const HerramientasControlCajaRoute = HerramientasControlCajaRouteImport.update({
  id: '/control-caja',
  path: '/control-caja',
  getParentRoute: () => HerramientasRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIdRoute = CursosIdRouteImport.update({
  id: '/cursos_/$id',
  path: '/cursos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProEmbedRoute = ApiPublicProEmbedRouteImport.update({
  id: '/api/public/pro-embed',
  path: '/api/public/pro-embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNovedadesRoute = ApiPublicNovedadesRouteImport.update({
  id: '/api/public/novedades',
  path: '/api/public/novedades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaterialDownloadRoute =
  ApiPublicMaterialDownloadRouteImport.update({
    id: '/api/public/material-download',
    path: '/api/public/material-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLessonEmbedRoute = ApiPublicLessonEmbedRouteImport.update({
  id: '/api/public/lesson-embed',
  path: '/api/public/lesson-embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBunnyThumbsRoute = ApiPublicBunnyThumbsRouteImport.update({
  id: '/api/public/bunny-thumbs',
  path: '/api/public/bunny-thumbs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBunnySyncRoute = ApiPublicBunnySyncRouteImport.update({
  id: '/api/public/bunny-sync',
  path: '/api/public/bunny-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/asistente': typeof AsistenteRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/herramientas': typeof HerramientasRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/planes': typeof PlanesRoute
  '/privacidad': typeof PrivacidadRoute
  '/reembolsos': typeof ReembolsosRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sala-pro': typeof SalaProRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/cursos/$id': typeof CursosIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/herramientas/control-caja': typeof HerramientasControlCajaRoute
  '/herramientas/dre': typeof HerramientasDreRoute
  '/herramientas/dre-mensual': typeof HerramientasDreMensualRoute
  '/herramientas/fichas-tecnicas': typeof HerramientasFichasTecnicasRoute
  '/herramientas/monitor-cmv': typeof HerramientasMonitorCmvRoute
  '/herramientas/punto-equilibrio': typeof HerramientasPuntoEquilibrioRoute
  '/herramientas/': typeof HerramientasIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/bunny-sync': typeof ApiPublicBunnySyncRoute
  '/api/public/bunny-thumbs': typeof ApiPublicBunnyThumbsRoute
  '/api/public/lesson-embed': typeof ApiPublicLessonEmbedRoute
  '/api/public/material-download': typeof ApiPublicMaterialDownloadRoute
  '/api/public/novedades': typeof ApiPublicNovedadesRoute
  '/api/public/pro-embed': typeof ApiPublicProEmbedRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/asistente': typeof AsistenteRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/planes': typeof PlanesRoute
  '/privacidad': typeof PrivacidadRoute
  '/reembolsos': typeof ReembolsosRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sala-pro': typeof SalaProRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/cursos/$id': typeof CursosIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/herramientas/control-caja': typeof HerramientasControlCajaRoute
  '/herramientas/dre': typeof HerramientasDreRoute
  '/herramientas/dre-mensual': typeof HerramientasDreMensualRoute
  '/herramientas/fichas-tecnicas': typeof HerramientasFichasTecnicasRoute
  '/herramientas/monitor-cmv': typeof HerramientasMonitorCmvRoute
  '/herramientas/punto-equilibrio': typeof HerramientasPuntoEquilibrioRoute
  '/herramientas': typeof HerramientasIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/bunny-sync': typeof ApiPublicBunnySyncRoute
  '/api/public/bunny-thumbs': typeof ApiPublicBunnyThumbsRoute
  '/api/public/lesson-embed': typeof ApiPublicLessonEmbedRoute
  '/api/public/material-download': typeof ApiPublicMaterialDownloadRoute
  '/api/public/novedades': typeof ApiPublicNovedadesRoute
  '/api/public/pro-embed': typeof ApiPublicProEmbedRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/asistente': typeof AsistenteRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/herramientas': typeof HerramientasRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/planes': typeof PlanesRoute
  '/privacidad': typeof PrivacidadRoute
  '/reembolsos': typeof ReembolsosRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sala-pro': typeof SalaProRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/cursos_/$id': typeof CursosIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/herramientas/control-caja': typeof HerramientasControlCajaRoute
  '/herramientas/dre': typeof HerramientasDreRoute
  '/herramientas/dre-mensual': typeof HerramientasDreMensualRoute
  '/herramientas/fichas-tecnicas': typeof HerramientasFichasTecnicasRoute
  '/herramientas/monitor-cmv': typeof HerramientasMonitorCmvRoute
  '/herramientas/punto-equilibrio': typeof HerramientasPuntoEquilibrioRoute
  '/herramientas/': typeof HerramientasIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/bunny-sync': typeof ApiPublicBunnySyncRoute
  '/api/public/bunny-thumbs': typeof ApiPublicBunnyThumbsRoute
  '/api/public/lesson-embed': typeof ApiPublicLessonEmbedRoute
  '/api/public/material-download': typeof ApiPublicMaterialDownloadRoute
  '/api/public/novedades': typeof ApiPublicNovedadesRoute
  '/api/public/pro-embed': typeof ApiPublicProEmbedRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/asistente'
    | '/cursos'
    | '/dashboard'
    | '/forgot-password'
    | '/herramientas'
    | '/login'
    | '/mcp'
    | '/perfil'
    | '/planes'
    | '/privacidad'
    | '/reembolsos'
    | '/registro'
    | '/reset-password'
    | '/sala-pro'
    | '/sitemap.xml'
    | '/terminos'
    | '/tienda'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checkout/return'
    | '/cursos/$id'
    | '/email/unsubscribe'
    | '/herramientas/control-caja'
    | '/herramientas/dre'
    | '/herramientas/dre-mensual'
    | '/herramientas/fichas-tecnicas'
    | '/herramientas/monitor-cmv'
    | '/herramientas/punto-equilibrio'
    | '/herramientas/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/bunny-sync'
    | '/api/public/bunny-thumbs'
    | '/api/public/lesson-embed'
    | '/api/public/material-download'
    | '/api/public/novedades'
    | '/api/public/pro-embed'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/asistente'
    | '/cursos'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/perfil'
    | '/planes'
    | '/privacidad'
    | '/reembolsos'
    | '/registro'
    | '/reset-password'
    | '/sala-pro'
    | '/sitemap.xml'
    | '/terminos'
    | '/tienda'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checkout/return'
    | '/cursos/$id'
    | '/email/unsubscribe'
    | '/herramientas/control-caja'
    | '/herramientas/dre'
    | '/herramientas/dre-mensual'
    | '/herramientas/fichas-tecnicas'
    | '/herramientas/monitor-cmv'
    | '/herramientas/punto-equilibrio'
    | '/herramientas'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/bunny-sync'
    | '/api/public/bunny-thumbs'
    | '/api/public/lesson-embed'
    | '/api/public/material-download'
    | '/api/public/novedades'
    | '/api/public/pro-embed'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/asistente'
    | '/cursos'
    | '/dashboard'
    | '/forgot-password'
    | '/herramientas'
    | '/login'
    | '/mcp'
    | '/perfil'
    | '/planes'
    | '/privacidad'
    | '/reembolsos'
    | '/registro'
    | '/reset-password'
    | '/sala-pro'
    | '/sitemap.xml'
    | '/terminos'
    | '/tienda'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checkout/return'
    | '/cursos_/$id'
    | '/email/unsubscribe'
    | '/herramientas/control-caja'
    | '/herramientas/dre'
    | '/herramientas/dre-mensual'
    | '/herramientas/fichas-tecnicas'
    | '/herramientas/monitor-cmv'
    | '/herramientas/punto-equilibrio'
    | '/herramientas/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/bunny-sync'
    | '/api/public/bunny-thumbs'
    | '/api/public/lesson-embed'
    | '/api/public/material-download'
    | '/api/public/novedades'
    | '/api/public/pro-embed'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AsistenteRoute: typeof AsistenteRoute
  CursosRoute: typeof CursosRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HerramientasRoute: typeof HerramientasRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PerfilRoute: typeof PerfilRoute
  PlanesRoute: typeof PlanesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ReembolsosRoute: typeof ReembolsosRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalaProRoute: typeof SalaProRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosRoute: typeof TerminosRoute
  TiendaRoute: typeof TiendaRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CursosIdRoute: typeof CursosIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBunnySyncRoute: typeof ApiPublicBunnySyncRoute
  ApiPublicBunnyThumbsRoute: typeof ApiPublicBunnyThumbsRoute
  ApiPublicLessonEmbedRoute: typeof ApiPublicLessonEmbedRoute
  ApiPublicMaterialDownloadRoute: typeof ApiPublicMaterialDownloadRoute
  ApiPublicNovedadesRoute: typeof ApiPublicNovedadesRoute
  ApiPublicProEmbedRoute: typeof ApiPublicProEmbedRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala-pro': {
      id: '/sala-pro'
      path: '/sala-pro'
      fullPath: '/sala-pro'
      preLoaderRoute: typeof SalaProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolsos': {
      id: '/reembolsos'
      path: '/reembolsos'
      fullPath: '/reembolsos'
      preLoaderRoute: typeof ReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas': {
      id: '/herramientas'
      path: '/herramientas'
      fullPath: '/herramientas'
      preLoaderRoute: typeof HerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas/': {
      id: '/herramientas/'
      path: '/'
      fullPath: '/herramientas/'
      preLoaderRoute: typeof HerramientasIndexRouteImport
      parentRoute: typeof HerramientasRoute
    }
    '/herramientas/punto-equilibrio': {
      id: '/herramientas/punto-equilibrio'
      path: '/punto-equilibrio'
      fullPath: '/herramientas/punto-equilibrio'
      preLoaderRoute: typeof HerramientasPuntoEquilibrioRouteImport
      parentRoute: typeof HerramientasRoute
    }
    '/herramientas/monitor-cmv': {
      id: '/herramientas/monitor-cmv'
      path: '/monitor-cmv'
      fullPath: '/herramientas/monitor-cmv'
      preLoaderRoute: typeof HerramientasMonitorCmvRouteImport
      parentRoute: typeof HerramientasRoute
    }
    '/herramientas/fichas-tecnicas': {
      id: '/herramientas/fichas-tecnicas'
      path: '/fichas-tecnicas'
      fullPath: '/herramientas/fichas-tecnicas'
      preLoaderRoute: typeof HerramientasFichasTecnicasRouteImport
      parentRoute: typeof HerramientasRoute
    }
    '/herramientas/dre-mensual': {
      id: '/herramientas/dre-mensual'
      path: '/dre-mensual'
      fullPath: '/herramientas/dre-mensual'
      preLoaderRoute: typeof HerramientasDreMensualRouteImport
      parentRoute: typeof HerramientasRoute
    }
    '/herramientas/dre': {
      id: '/herramientas/dre'
      path: '/dre'
      fullPath: '/herramientas/dre'
      preLoaderRoute: typeof HerramientasDreRouteImport
      parentRoute: typeof HerramientasRoute
    }
    '/herramientas/control-caja': {
      id: '/herramientas/control-caja'
      path: '/control-caja'
      fullPath: '/herramientas/control-caja'
      preLoaderRoute: typeof HerramientasControlCajaRouteImport
      parentRoute: typeof HerramientasRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos_/$id': {
      id: '/cursos_/$id'
      path: '/cursos/$id'
      fullPath: '/cursos/$id'
      preLoaderRoute: typeof CursosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pro-embed': {
      id: '/api/public/pro-embed'
      path: '/api/public/pro-embed'
      fullPath: '/api/public/pro-embed'
      preLoaderRoute: typeof ApiPublicProEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/novedades': {
      id: '/api/public/novedades'
      path: '/api/public/novedades'
      fullPath: '/api/public/novedades'
      preLoaderRoute: typeof ApiPublicNovedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/material-download': {
      id: '/api/public/material-download'
      path: '/api/public/material-download'
      fullPath: '/api/public/material-download'
      preLoaderRoute: typeof ApiPublicMaterialDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lesson-embed': {
      id: '/api/public/lesson-embed'
      path: '/api/public/lesson-embed'
      fullPath: '/api/public/lesson-embed'
      preLoaderRoute: typeof ApiPublicLessonEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bunny-thumbs': {
      id: '/api/public/bunny-thumbs'
      path: '/api/public/bunny-thumbs'
      fullPath: '/api/public/bunny-thumbs'
      preLoaderRoute: typeof ApiPublicBunnyThumbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bunny-sync': {
      id: '/api/public/bunny-sync'
      path: '/api/public/bunny-sync'
      fullPath: '/api/public/bunny-sync'
      preLoaderRoute: typeof ApiPublicBunnySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HerramientasRouteChildren {
  HerramientasControlCajaRoute: typeof HerramientasControlCajaRoute
  HerramientasDreRoute: typeof HerramientasDreRoute
  HerramientasDreMensualRoute: typeof HerramientasDreMensualRoute
  HerramientasFichasTecnicasRoute: typeof HerramientasFichasTecnicasRoute
  HerramientasMonitorCmvRoute: typeof HerramientasMonitorCmvRoute
  HerramientasPuntoEquilibrioRoute: typeof HerramientasPuntoEquilibrioRoute
  HerramientasIndexRoute: typeof HerramientasIndexRoute
}

const HerramientasRouteChildren: HerramientasRouteChildren = {
  HerramientasControlCajaRoute: HerramientasControlCajaRoute,
  HerramientasDreRoute: HerramientasDreRoute,
  HerramientasDreMensualRoute: HerramientasDreMensualRoute,
  HerramientasFichasTecnicasRoute: HerramientasFichasTecnicasRoute,
  HerramientasMonitorCmvRoute: HerramientasMonitorCmvRoute,
  HerramientasPuntoEquilibrioRoute: HerramientasPuntoEquilibrioRoute,
  HerramientasIndexRoute: HerramientasIndexRoute,
}

const HerramientasRouteWithChildren = HerramientasRoute._addFileChildren(
  HerramientasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AsistenteRoute: AsistenteRoute,
  CursosRoute: CursosRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HerramientasRoute: HerramientasRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PerfilRoute: PerfilRoute,
  PlanesRoute: PlanesRoute,
  PrivacidadRoute: PrivacidadRoute,
  ReembolsosRoute: ReembolsosRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalaProRoute: SalaProRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosRoute: TerminosRoute,
  TiendaRoute: TiendaRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CursosIdRoute: CursosIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBunnySyncRoute: ApiPublicBunnySyncRoute,
  ApiPublicBunnyThumbsRoute: ApiPublicBunnyThumbsRoute,
  ApiPublicLessonEmbedRoute: ApiPublicLessonEmbedRoute,
  ApiPublicMaterialDownloadRoute: ApiPublicMaterialDownloadRoute,
  ApiPublicNovedadesRoute: ApiPublicNovedadesRoute,
  ApiPublicProEmbedRoute: ApiPublicProEmbedRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
